# Find libmusicaccess
#
# MUSICACCESS_INCLUDE_DIR - where to find musicaccess.hpp, etc.
# MUSICACCESS_LIBRARIES - List of libraries when using libmusicaccess.
# MUSICACCESS_FOUND - True if libmusicaccess found.

IF(MUSICACCESS_INCLUDE_DIR)
    # be silent, file already in cache
    SET(MUSICACCESS_FIND_QUIETLY TRUE)
ENDIF(MUSICACCESS_INCLUDE_DIR)

FIND_PATH(MUSICACCESS_INCLUDE_DIR musicaccess.hpp PATHS
        ${CMAKE_INSTALL_PREFIX}/include)

FIND_LIBRARY(MUSICACCESS_LIBRARY NAMES musicaccess PATHS
        /usr/lib /usr/local/lib /armle-v7/usr/lib /armle-v7/lib)

# Handle the QUIETLY and REQUIRED arguments and set MUSICACCESS_FOUND to TRUE if
# all listed variables are TRUE.
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(MUSICACCESS DEFAULT_MSG MUSICACCESS_LIBRARY MUSICACCESS_INCLUDE_DIR)

IF(MUSICACCESS_FOUND)
  SET(MUSICACCESS_LIBRARIES ${MUSICACCESS_LIBRARY})
ELSE(MUSICACCESS_FOUND)
  SET(MUSICACCESS_LIBRARIES)
  IF(REQUIRED)
    MESSAGE(FATAL_ERROR "Required library musicaccess not found.")
  ENDIF(REQUIRED)
ENDIF(MUSICACCESS_FOUND)

MARK_AS_ADVANCED(MUSICACCESS_INCLUDE_DIR MUSICACCESS_LIBRARY)
